/*
 * Author: Gleb Novodran <novodran@gmail.com>
 */
#include "GWSys.hpp"
#include "GWBase.hpp"
#include "GWList.hpp"
#include "GWVector.hpp"
#include "GWSphere.hpp"
#include "GWRay.hpp"
#include "GWColor.hpp"
#include "GWMatrix.hpp"
#include "GWQuaternion.hpp"
#include "GWTransform.hpp"
#include "GWCamera.hpp"
#include "GWMotion.hpp"
#include "GWImage.hpp"
#include "GWSphericalHarmonics.hpp"
#include "GWResource.hpp"
#include "GWModel.hpp"
#include "GWScene.hpp"